# Generated by Django 4.1.3 on 2022-12-27 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('AdID', models.AutoField(primary_key=True, serialize=False)),
                ('Price', models.IntegerField()),
                ('Title', models.CharField(max_length=120)),
                ('Description', models.CharField(blank=True, max_length=500, null=True)),
                ('Status', models.CharField(blank=True, max_length=30)),
                ('CreationDate', models.DateTimeField(blank=True)),
                ('SaleDate', models.DateTimeField(blank=True, null=True)),
                ('Photo', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('CustomerID', models.AutoField(primary_key=True, serialize=False)),
                ('DateSignUp', models.DateTimeField(blank=True)),
                ('FirstName', models.CharField(blank=True, max_length=30)),
                ('LastName', models.CharField(blank=True, max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('SellerID', models.AutoField(primary_key=True, serialize=False)),
                ('DateSignUp', models.DateTimeField(blank=True)),
                ('FirstName', models.CharField(blank=True, max_length=30)),
                ('LastName', models.CharField(blank=True, max_length=30)),
                ('Telephone', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('TypeID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=30)),
                ('NumBedrooms', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Flat',
            fields=[
                ('FlatID', models.AutoField(primary_key=True, serialize=False)),
                ('Area', models.FloatField()),
                ('Address', models.CharField(max_length=150)),
                ('Floor', models.IntegerField()),
                ('Balcony', models.BooleanField()),
                ('YearBuilt', models.IntegerField(null=True)),
                ('BuildTech', models.CharField(blank=True, max_length=30, null=True)),
                ('TypeID', models.ForeignKey(db_column='TypeID', on_delete=django.db.models.deletion.DO_NOTHING, to='estate_market.type')),
            ],
        ),
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Status', models.TextField()),
                ('AdID', models.ForeignKey(db_column='AdID', on_delete=django.db.models.deletion.DO_NOTHING, to='estate_market.ad')),
                ('CustomerID', models.ForeignKey(db_column='CustomerID', on_delete=django.db.models.deletion.DO_NOTHING, to='estate_market.customer')),
            ],
        ),
        migrations.AddField(
            model_name='ad',
            name='CustomerID',
            field=models.ForeignKey(blank=True, db_column='CustomerID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='estate_market.customer'),
        ),
        migrations.AddField(
            model_name='ad',
            name='FlatID',
            field=models.ForeignKey(db_column='FlatID', on_delete=django.db.models.deletion.DO_NOTHING, to='estate_market.flat'),
        ),
        migrations.AddField(
            model_name='ad',
            name='SellerID',
            field=models.ForeignKey(db_column='SellerID', on_delete=django.db.models.deletion.DO_NOTHING, to='estate_market.seller'),
        ),
    ]
