# Generated by Django 4.1.1 on 2022-10-11 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ads',
            fields=[
                ('AdID', models.AutoField(primary_key=True, serialize=False)),
                ('Status', models.CharField(blank=True, max_length=30)),
                ('CreationDate', models.DateTimeField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('CustomerID', models.AutoField(primary_key=True, serialize=False)),
                ('DateSignUp', models.DateTimeField(blank=True)),
                ('FirstName', models.CharField(blank=True, max_length=30)),
                ('LastName', models.CharField(blank=True, max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Sellers',
            fields=[
                ('SellerID', models.AutoField(primary_key=True, serialize=False)),
                ('DateSignUp', models.DateTimeField(blank=True)),
                ('FirstName', models.CharField(blank=True, max_length=30)),
                ('LastName', models.CharField(blank=True, max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Types',
            fields=[
                ('TypeID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=30)),
                ('NumBedrooms', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('OrderID', models.AutoField(primary_key=True, serialize=False)),
                ('Status', models.CharField(blank=True, max_length=30)),
                ('OrderStartDate', models.DateField(blank=True)),
                ('OrderEndDate', models.DateField(blank=True)),
                ('AdID', models.ForeignKey(db_column='AdID', on_delete=django.db.models.deletion.DO_NOTHING, to='estate_market.ads')),
                ('CustomerID', models.ForeignKey(db_column='CustomerID', on_delete=django.db.models.deletion.DO_NOTHING, to='estate_market.customers')),
            ],
        ),
        migrations.CreateModel(
            name='Flats',
            fields=[
                ('FlatID', models.AutoField(primary_key=True, serialize=False)),
                ('Area', models.FloatField()),
                ('Address', models.CharField(max_length=150)),
                ('Floor', models.IntegerField()),
                ('Balcony', models.BooleanField()),
                ('YearBuilt', models.IntegerField(null=True)),
                ('BuildTech', models.CharField(blank=True, max_length=30, null=True)),
                ('Type', models.ForeignKey(db_column='TypeID', on_delete=django.db.models.deletion.DO_NOTHING, to='estate_market.types')),
            ],
        ),
        migrations.AddField(
            model_name='ads',
            name='FlatID',
            field=models.ForeignKey(db_column='FlatID', on_delete=django.db.models.deletion.DO_NOTHING, to='estate_market.flats'),
        ),
        migrations.AddField(
            model_name='ads',
            name='SellerID',
            field=models.ForeignKey(db_column='SellerID', on_delete=django.db.models.deletion.DO_NOTHING, to='estate_market.sellers'),
        ),
    ]
