# Generated by Django 4.1.1 on 2022-10-12 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estate_market', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ads',
            new_name='Ad',
        ),
        migrations.RenameModel(
            old_name='Customers',
            new_name='Customer',
        ),
        migrations.RenameModel(
            old_name='Flats',
            new_name='Flat',
        ),
        migrations.RenameModel(
            old_name='Orders',
            new_name='Order',
        ),
        migrations.RenameModel(
            old_name='Sellers',
            new_name='Seller',
        ),
        migrations.RenameModel(
            old_name='Types',
            new_name='Type',
        ),
    ]
