# Generated by Django 4.1.3 on 2022-12-28 02:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('estate_market', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basket',
            name='CustomerID',
        ),
        migrations.AddField(
            model_name='basket',
            name='UserID',
            field=models.ForeignKey(db_column='UserID', default=1, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
