# Generated by Django 4.1.3 on 2022-12-28 02:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('estate_market', '0002_remove_basket_customerid_basket_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='UserID',
            field=models.ForeignKey(db_column='UserID', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
