# Generated by Django 4.1.1 on 2022-10-12 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate_market', '0002_rename_ads_ad_rename_customers_customer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='Description',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
