# Generated by Django 4.1.1 on 2022-10-12 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate_market', '0003_ad_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='Title',
            field=models.CharField(default='Квартира', max_length=120),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ad',
            name='Description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
