# Generated by Django 4.1.1 on 2022-10-12 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate_market', '0004_ad_title_alter_ad_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='Telephone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
