# Generated by Django 4.1.1 on 2022-10-12 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estate_market', '0005_seller_telephone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flat',
            old_name='Type',
            new_name='TypeID',
        ),
    ]
