# Generated by Django 4.1.1 on 2022-10-12 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate_market', '0006_rename_type_flat_typeid'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='Price',
            field=models.IntegerField(default=5000000),
            preserve_default=False,
        ),
    ]
