# Generated by Django 4.1.1 on 2022-10-25 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estate_market', '0007_ad_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='CustomerID',
            field=models.ForeignKey(blank=True, db_column='CustomerID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='estate_market.customer'),
        ),
        migrations.AddField(
            model_name='ad',
            name='SaleDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
