# Generated by Django 4.1.3 on 2022-12-25 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estate_market', '0008_ad_customerid_ad_saledate_delete_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Status', models.TextField()),
                ('AdID', models.ForeignKey(db_column='AdID', on_delete=django.db.models.deletion.DO_NOTHING, to='estate_market.ad')),
                ('CustomerID', models.ForeignKey(db_column='CustomerID', on_delete=django.db.models.deletion.DO_NOTHING, to='estate_market.customer')),
            ],
        ),
    ]
