# Generated by Django 4.1.3 on 2022-12-27 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate_market', '0009_basket'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='Photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
